### PR TITLE
fixed jquery issue described in #44

### PR DESCRIPTION
**Pull request by dpotkoc**

### CODE REVIEW

**Comment by FoulBachelor** [comment]
Hi @kasperth,

The difference between this and the current live version, is that this PR uses a jquery and jqueryUI dependecy, instead of vanilla JS.

In my view this PR offers a more error prone approach to doing the same thing. Can you clarify in which way you see the PR as an improvement over what is currently in the livesearch template?

**Comment by kasperth** [comment]
@FoulBachelor the primary reason for me pushing this PR is actually because it solves an issue where the Search URL breaks and returns a 404 error. Example. Enter "shoe" in the search field and you were directed to domain.com/search=shoes, search for "shoes" again and you were directed to domain.com/search=shoe/search=shoe (which was broken) The new URL slug was added in addition to the old slug.

**Comment by FoulBachelor** [comment]
Ah this is useful, are you guys running a single page app kind of setup where the URL is manipulated to reflect the route. 

In that case it would make sense that the rerender event is tied to the Magento2 ajax. I will see about adding this in for you.

**Comment by FoulBachelor** [comment]
Hello Kasper,

I have made some changes to the action on the search page.

https://github.com/clerkio/clerk-magento2/commit/ba87beb4dfdc64bec8627c9a29cb64f800f00728

Please note that the getUrl function does not exist in the associated block, so merging this code as is is a no go.

That said, the current change takes the relative path of the search page route and concatenates it to the base route for the website view, so that the URL is always absolute.

If you experience that your searches consecutively adds fragments to the URL, it goes not come from this section of code, but would be something being affected by the individual design template in use.

I have previously seen some templates implemented for clients with search inputs which were not nested in a form element, where the redirect was create by adding JS to the template.

Something to the effect of:

document.querySelector('#search_input').addEventListener('keyup', function(e){
if(e.keyCode == 13){
window.location.href = window.location.origin + 'catalogsearch/result?q=' + urlencode(document.querySelector('#search_input').value);
}
});

Since I have no view of the individual site or case in this thread, this is just a theory for the possible cause if based on other implementations I have seen on PWA's.

**Pull request closed without merging**
